name: Scraper Worker

on:
  schedule:
    - cron: '30 11 * * *'  # Runs every day at 11:30 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change directory to 'packages/scraper'
      run: cd packages/scraper

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Install playwright deps
      run: npx playwright install --with-deps chromium

    - name: Run Scraper
      run: npx ts-node index.ts